### ISSUE TITLE
django-pipeline's documentation doesn't update after releases

### ISSUE THREAD

**Issue by peymanslh** [jazzband-roadies/help#353]
Recently we had two releases for [django-pileline](https://github.com/jazzband/django-pipeline) but the documentation was not updated.
Its last build in Read-The-Docs failed more than a year ago. https://readthedocs.org/projects/django-pipeline/builds/

**Comment by hugovk** [comment]
The first thing to do is create a Read the Docs config file, it's now required:

https://blog.readthedocs.com/migrate-configuration-v2/

See some other Jazzband projects and:

https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by peymanslh** [comment]
Thanks @hugovk

**Comment by blaisep** [comment]
@peymanslh 

try creating this `.readthedocs.yaml`, then lmk if we can close this ticket and send me a url to the recent docs please.

```yaml
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py

python:
  install:
  - requirements: requirements.txt
  - method: pip
    path: .
```

you may have to adjust paths, but I think I got it right for your project.
